### ISSUE TITLE
Cursor position is not updated correctly when editing an entry

### ISSUE THREAD

**Issue by rovitsky** [journiv/journiv-app#95]
If I edit an entry and find a typo somewhere above in the text, I tend to use arrow keys to get to it without touching the mouse. But I've noticed that the cursor position doesn't update continuously if I hold "up" button - it is updated only when I release the button. This makes it difficult to get to the specific line.
I can provide video of this bug if needed.

Journiv version: swalabtech/journiv-app:0.1.0-beta.6 (2025-11-14)
Firefox 145.0

**Comment by swalabtech** [comment]
Thank you @rovitsky for reporting this. 

I will try to reproduce it on my end.

**Comment by swalabtech** [comment]
This will be resolved in https://github.com/journiv/journiv-app/issues/71

**Comment by swalabtech** [comment]
This should be fixed now with the new markdown and formatting toolbar support on `main`. Please give it a try.

**Comment by rovitsky** [comment]
@swalabtech I can still reproduce this on `0.1.0-beta.9`. Do i need to specifically pull `main`?
I can try to record this later, if you need a visual example, but it will take me some time to set up the screen capture.

**Comment by swalabtech** [comment]
Can you please make a small recording and share it?

Which OS and browser are you using?
